---
versionStoreType: IN_MEMORY
tracing:
  enabled: true
metrics:
  enabled: true
  tags:
    service: nessie
    environment: dev
service:
  sessionAffinity: ClientIP
catalog:
  enabled: true
  iceberg:
    # the sample bucket cannot be checked
    objectStoresHealthCheckEnabled: false
    defaultWarehouse: warehouse1
    configDefaults:
      default1: value1
      default2: value2
    configOverrides:
      override1: value1
      override2: value2
    warehouses:
    - name: warehouse1
      location: s3://bucket1.prod-us/warehouse
      configDefaults:
        default1: value11
        default2: value22
      configOverrides:
        override1: value11
        override2: value22
  storage:
    s3:
      transport:
        readTimeout: PT1M
      defaultOptions:
        region: us-west-2
        endpoint: s3.amazonaws.com
#        accessKeySecret:
#          name: s3-access-key
#          awsAccessKeyId: access-key-id
#          awsSecretAccessKey: secret-access-key
      buckets:
        - name: bucket1.prod-us
          endpoint: prod-us.s3.amazonaws.com
          region: us-east-1
#          accessKeySecret:
#            name: s3-access-key
#            awsAccessKeyId: access-key-id
#            awsSecretAccessKey: secret-access-key
    gcs:
      transport:
        readTimeout: PT1M
      defaultOptions:
        host: https://storage.googleapis.com
#        authCredentialsJsonSecret:
#          name: gcs-credentials
#          key: credentials.json
      buckets:
      - name: bucket1.prod-us
        projectId: project-id
#        authCredentialsJsonSecret:
#          name: gcs-credentials
#          key: credentials.json

    adls:
      transport:
        readTimeout: PT1M
      advancedConfig:
        flat1.flat2.key1: value1
        nested1:
          nested2:
            key2: value2
            key3: value3
      defaultOptions:
        endpoint: adl://account.azuredatalakestore.net
#        accountSecret:
#          name: adls-account-secret
#          accountName: account-name
#          accountKey: account-key
      filesystems:
      - name: filesystem1
        endpoint: adl://account.azuredatalakestore.net
#        accountSecret:
#          name: adls-account-secret
#          accountName: account-name
#          accountKey: account-key
