{{- if and (.Values.airflow.dags.gitSync.enabled)  (.Values.airflow.dags.gitSync.credentialsSecret) }}
# If passwordSecretName is not set, we will either use the set password, or use the generated one
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.airflow.dags.gitSync.credentialsSecret }}
  labels:        
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
type: Opaque
data:
  GIT_SYNC_PASSWORD: {{  .Values.secret.gitSync.password | b64enc | quote }}
  GIT_SYNC_USERNAME: {{  .Values.secret.gitSync.username | b64enc | quote }}
{{- end }}

---

apiVersion: v1
kind: Secret
metadata:
  name: awscreds
type: Opaque
data:
  awsAccessKeyId: {{  .Values.secret.awscreds.awsAccessKeyId | b64enc | quote }} 
  awsSecretAccessKey: {{  .Values.secret.awscreds.awsSecretAccessKey | b64enc | quote }}  


---

apiVersion: v1
kind: Secret
metadata:
  name: rada-platform-postgresql-secret
type: kubernetes.io/basic-auth
data:
  username: {{  .Values.secret.postgresql.username | b64enc | quote }}
  password: {{  .Values.secret.postgresql.password | b64enc | quote }}
